Analyzing Student Enrollment Trends**

**Dataset Generation**

In [1]:
pip install faker

Collecting fakerNote: you may need to restart the kernel to use updated packages.

  Obtaining dependency information for faker from https://files.pythonhosted.org/packages/40/f7/c88578e2bbb7e8940dd552d175300a6e8e9ee2f8d84fddad8e6acfe0e6cf/Faker-23.2.1-py3-none-any.whl.metadata
  Downloading Faker-23.2.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\mahmo\anaconda3\lib\site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\mahmo\anaconda3\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-23.2.1-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 660.6 kB/s eta 0:00:03
   - -------------------------------------- 0.1/1.7 MB 550.5 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/1.7 MB 655.4 kB/s eta 0:00:03
   --- ------------------------------------ 0.1/1.7 MB 774.0 kB/s eta 0:00:03
   ----- ---------------------------------- 0.2/1.7 MB 1.2 MB/s eta 0:00:02
   -------- ------------------------------- 0.4/1.7 MB 1.2 MB/s eta 0:00:02
   ---------- ----------------------------- 0.5/1.7 MB 1.5 MB/s eta 0:00:01
   ------------- -------------------------- 0.6/1.7 MB 1.6 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.7 MB 1.7 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.7 MB 1.7 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.7 MB 1.7 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.7 MB 1.7 MB/s eta 0:00:01
   -------------------------- ------------- 1.2/1.7 MB 2.0 MB/s eta 0:00:01
   --------------------------- ------------ 1.2/1.7 MB 2.0 MB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.7 MB 1.9 MB/s eta 0:00:01
   -------------------------------- ------- 1.4/1.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 1.5/1.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 1.5/1.7 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.7 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  1.7/1.7 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-23.2.1

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

fake = Faker()

# Set up data variables
grades = ['9th', '10th', '11th', '12th']
subjects = ['Math', 'Science', 'English', 'History', 'Art']
years = range(2019, 2024)

In [3]:
# Generate student records
data = []
for i in range(500):
    data.append([
        fake.name(),
        fake.date(),
        random.choice(grades),
        random.choice(subjects),
        random.choice(years),
        np.random.randint(60, 101)  # Random Score
    ])

In [4]:
# Create the DataFrame
df = pd.DataFrame(data, columns=['Student Name', 'Enrol date', 'Grade', 'Subject', 'Year', 'Score'])
df.head()

  Student Name  Enrol date Grade  Subject  Year  Score
0  Leah Barber  1984-05-03  10th  English  2021     87
1   Tony Scott  2006-12-04   9th     Math  2023     62
2  Rita Monroe  1982-02-26   9th  English  2020     74
3    Kim Davis  1972-10-21  12th     Math  2021     76
4   Steven Ray  1994-06-11   9th     Math  2022     84

**Project Instructions (For Students)**

Welcome to our Pandas project! We'll explore a dataset of student enrollment records to answer some key questions about trends in our school district.

**Tasks**

1. **Understanding with `.iloc`**
   * How many students are in the 11th grade? (Hint: Filter and then get the length)
   * Display the 'Subject' and 'Score' for the 5th student record.
   * Which students scored above 90 in the year 2022?  

2. **Making Changes with `.str`**
   * It looks like student names aren't consistent. Make all names lowercase.

3. **Dates with `.dt`**
   * Create a 'Month' column by extracting the month from a new 'Enrol Date' column 
   * How many students enrolled each month across all years?

4. **Stats and Counts**
   * What's the overall average score?
   * Which grade level has the most students?

## Solution

**Tasks**

1. **Filtering and selecting**
   * How many students are in the 11th grade? (Hint: Filter and then get the length)

In [ ]:
df

        Student Name Grade  Subject  Year  Score
0       James Rogers  10th      Art  2022     88
1       Brandon Rush   9th  English  2020     66
2     Charlene Riley  12th  Science  2022     62
3    Jessica Fuentes  12th  History  2020     89
4     Krystal Murphy   9th  History  2021     91
..               ...   ...      ...   ...    ...
495     Amy Mcdonald  10th     Math  2019     81
496     Jack Jimenez   9th  Science  2022     89
497   Taylor Barrett  12th  History  2023     91
498    Laura Huffman   9th  History  2020     72
499  Jeffrey Mendoza  12th      Art  2019     92

[500 rows x 5 columns]

In [ ]:
df[df.Grade == "11th"]

          Student Name Grade  Subject  Year  Score
13      Kristen Morrow  11th  History  2020     78
17          Ann Murphy  11th  Science  2023     86
27       Linda Sanders  11th  Science  2019     71
34    Christine Horton  11th      Art  2021     73
37      Ashley Proctor  11th  English  2022     98
..                 ...   ...      ...   ...    ...
479  Katherine Shelton  11th  English  2023     66
483        Joel Taylor  11th      Art  2023     74
490  Oscar Blankenship  11th  History  2021     86
492    Gregory Coleman  11th      Art  2020     88
494  William Henderson  11th  English  2021    100

[121 rows x 5 columns]

In [ ]:
df.query('Grade  == "11th"')

          Student Name Grade  Subject  Year  Score
13      Kristen Morrow  11th  History  2020     78
17          Ann Murphy  11th  Science  2023     86
27       Linda Sanders  11th  Science  2019     71
34    Christine Horton  11th      Art  2021     73
37      Ashley Proctor  11th  English  2022     98
..                 ...   ...      ...   ...    ...
479  Katherine Shelton  11th  English  2023     66
483        Joel Taylor  11th      Art  2023     74
490  Oscar Blankenship  11th  History  2021     86
492    Gregory Coleman  11th      Art  2020     88
494  William Henderson  11th  English  2021    100

[121 rows x 5 columns]

In [ ]:
df.loc[df['Grade'] == "11th"]

          Student Name Grade  Subject  Year  Score
13      Kristen Morrow  11th  History  2020     78
17          Ann Murphy  11th  Science  2023     86
27       Linda Sanders  11th  Science  2019     71
34    Christine Horton  11th      Art  2021     73
37      Ashley Proctor  11th  English  2022     98
..                 ...   ...      ...   ...    ...
479  Katherine Shelton  11th  English  2023     66
483        Joel Taylor  11th      Art  2023     74
490  Oscar Blankenship  11th  History  2021     86
492    Gregory Coleman  11th      Art  2020     88
494  William Henderson  11th  English  2021    100

[121 rows x 5 columns]

   * Display the 'Subject' and 'Score' for the 5th student record.

In [ ]:
df.loc[4, ["Subject", "Score"]]

Subject    History
Score           91
Name: 4, dtype: object

2. **Filtering Data**
   * Which students scored above 90 in the year 2022?

In [ ]:
df

        Student Name Grade  Subject  Year  Score
0       James Rogers  10th      Art  2022     88
1       Brandon Rush   9th  English  2020     66
2     Charlene Riley  12th  Science  2022     62
3    Jessica Fuentes  12th  History  2020     89
4     Krystal Murphy   9th  History  2021     91
..               ...   ...      ...   ...    ...
495     Amy Mcdonald  10th     Math  2019     81
496     Jack Jimenez   9th  Science  2022     89
497   Taylor Barrett  12th  History  2023     91
498    Laura Huffman   9th  History  2020     72
499  Jeffrey Mendoza  12th      Art  2019     92

[500 rows x 5 columns]

In [ ]:
df.loc[df["Score"] > 90]

          Student Name Grade  Subject  Year  Score
4       Krystal Murphy   9th  History  2021     91
11          Ethan Rios  12th     Math  2023    100
18       Amanda Romero   9th      Art  2023     96
21           Mary Pham   9th     Math  2023     99
25     Brittney Valdez   9th     Math  2020     92
..                 ...   ...      ...   ...    ...
485      Natalie Evans  12th  English  2023     92
487      Leah Peterson   9th  Science  2021     92
494  William Henderson  11th  English  2021    100
497     Taylor Barrett  12th  History  2023     91
499    Jeffrey Mendoza  12th      Art  2019     92

[116 rows x 5 columns]

2. **Making Changes with `.str`**
   * It looks like student names aren't consistent. Make all names lowercase.

In [ ]:
df['Student Name'] = df['Student Name'].str.lower()

3. **Dates with `.dt`**
   * Create a 'Month' column by extracting the month from a new 'Enrol Date' column

In [7]:
df['Enrol date'] = pd.to_datetime(df['Enrol date'])

In [8]:
df['month'] = df['Enrol date'].dt.month


   * How many students enrolled each month across all years?

In [9]:
df['month'].value_counts()

month
7     50
5     49
2     48
12    47
3     47
1     45
10    43
6     42
4     36
9     36
11    35
8     22
Name: count, dtype: int64


4. **Stats and Counts**
   * What's the overall average score?

In [11]:
df['Score'].mean()

79.998

   * Which grade level has the most students?

In [10]:
df['Grade'].value_counts()

Grade
9th     142
12th    123
11th    122
10th    113
Name: count, dtype: int64